[versions]
agp = "8.5.2"
appcompat = "1.7.0"
material = "1.12.0"
preference = "1.2.1"
ftpserver = "1.2.0"
mina = "2.1.6"
slf4j = "1.7.36"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
ftpserver-core = { module = "org.apache.ftpserver:ftpserver-core", version.ref = "ftpserver" }
ftplet-api = { module = "org.apache.ftpserver:ftplet-api", version.ref = "ftpserver" }
mina-core = { module = "org.apache.mina:mina-core", version.ref = "mina" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

